# Project information
site_name: Руководство по HTML и CSS
site_description: Учебник по разработке сайтов на языках разметки HTML и CSS
site_author: qepard
site_url: https://qepard.github.io/html-css-manual
docs_dir: book_src
site_dir: docs

# Copyright
copyright: Copyright &copy; 2023 qepard

# Configuration
theme:
  features:
    - header.autohide
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.sections
    - navigation.top
    - content.code.copy
    - toc.follow
  name: material
  language: ru
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: fontawesome/solid/code

# Extras
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/qepard/html-css-manual
      name: GitHub
  # alternate:
  #   - name: English
  #     link: /en/index.md
  #     lang: en
  #   - name: Russian
  #     link: /
  #     lang: ru

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - meta
  - attr_list
  - toc:
      permalink: false

# Navigation
nav:
  - 'Приветствие': index.md
  - 'Введение': intro.md
  - HTML:
    - 'Знакомство с HTML': html/index.md
  - CSS:
    - 'Знакомство с CSS': css/index.md

plugins:
  - search:
      lang:
        - en
        - ru
